import { test, expect } from '@playwright/test'

test('create, edit, preview, publish and clone a template', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => dialog.accept())
  await page.goto('/baypdf')
  await page.getByRole('button', { name: '+ New template' }).first().click()
  const form = page.getByRole('dialog')
  const name = 'Studio certificate ' + Date.now()
  await form.getByLabel('Template name').fill(name)
  await form.getByLabel('Document type').selectOption('certificate')
  await form.getByRole('button', { name: 'Create template' }).click()
  await expect(page.getByRole('heading', { name })).toBeVisible()
  await page.getByRole('button', { name: 'T Text', exact: true }).click()
  await page.getByLabel('Content', { exact: true }).fill('Certificate of participation')
  await page.getByLabel('Font size').fill('22')
  await page.getByLabel('Width', { exact: true }).fill('170')
  await page.getByLabel('Height', { exact: true }).fill('30')
  await page.getByLabel('Y', { exact: true }).fill('30')
  await page.getByRole('button', { name: /Recipient name/ }).click()
  await page.getByLabel('Y', { exact: true }).fill('75')
  await page.getByLabel('Font size').fill('24')
  await page.getByLabel('Width', { exact: true }).fill('170')
  await page.getByLabel('Height', { exact: true }).fill('30')
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Draft saved')
  await expect(page.getByRole('button', { name: 'Save draft', exact: true })).toBeDisabled()
  await page.screenshot({ path: '.artifacts/studio-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'PDF preview' }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'PDF preview' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download PDF' })).toHaveAttribute('href', /^blob:/)
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: /Publish version/ }).click()
  await expect(page.getByRole('button', { name: 'Create new draft' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'T Text', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Create new draft' }).click()
  await expect(page.getByRole('combobox', { name: 'Version', exact: true })).toContainText('Version 2')
  await expect(page.getByRole('button', { name: 'T Text', exact: true })).toBeEnabled()
  expect(errors).toEqual([])
})

test('German shell and mobile layout remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/baypdf?locale=de')
  await expect(page.getByRole('button', { name: '+ Neue Vorlage' }).first()).toBeVisible()
  await page.getByRole('button', { name: '+ Neue Vorlage' }).first().click()
  await page.getByRole('dialog').getByLabel('Vorlagenname').fill('Mobile Vorlage ' + Date.now())
  await page.getByRole('dialog').getByRole('button', { name: 'Vorlage erstellen' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Mobile Vorlage')
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  expect(overflow).toBe(false)
  await page.screenshot({ path: '.artifacts/studio-mobile.png', fullPage: true })
})
